// Serves files generated by the extraction pipeline (Phase 1 + Phase 3) so the
// SPA can iframe them from the result panel. Each /api/extract run writes to
// output/<slug>/ on disk; this route streams those files back over HTTP.
//
// Why an API route instead of public/ static serving? On Vercel public/ is
// build-time only — files written at runtime are not visible to the static
// handler. This route reads from process.cwd()/output/ at request time so the
// same code works in dev (pnpm dev) and prod (Vercel function disk).
//
// Security: this route is the ONLY way the SPA can read out/<slug>/* files,
// so it must reject anything that escapes the output root. Symlinks, ../, NUL
// bytes, and absolute paths are all rejected via realpath comparison.

import * as fs from "fs";
import * as path from "path";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const OUTPUT_ROOT = path.resolve(process.cwd(), "output");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path: segments } = await params;

  // ── Defense in depth ──────────────────────────────────────────────────
  // (1) Reject segments containing path-traversal or NUL bytes outright.
  // (2) Resolve to an absolute path.
  // (3) Verify the resolved path is genuinely inside OUTPUT_ROOT.
  for (const seg of segments) {
    if (seg.includes("..") || seg.includes("\0") || seg.includes("\\")) {
      return new Response("Bad path", { status: 400 });
    }
  }

  const requested = path.resolve(OUTPUT_ROOT, ...segments);
  if (!requested.startsWith(OUTPUT_ROOT + path.sep) && requested !== OUTPUT_ROOT) {
    return new Response("Forbidden", { status: 403 });
  }

  if (!fs.existsSync(requested)) {
    return new Response("Not found", { status: 404 });
  }

  const stat = fs.statSync(requested);
  if (!stat.isFile()) {
    return new Response("Not a file", { status: 400 });
  }

  const ext = path.extname(requested).toLowerCase();
  const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";

  const buf = fs.readFileSync(requested);
  return new Response(new Uint8Array(buf), {
    headers: {
      "content-type": contentType,
      "content-length": String(buf.length),
      // Generated artifacts change every extraction — no caching.
      "cache-control": "no-store",
    },
  });
}
