import type { ReactNode } from "react";

// Per-brand download bar that sits at the top of the gallery brand page.
// Layout: secondary artifacts (tokens.json / tailwind.css / shadcn-theme.css)
// pinned to the LEFT, the primary DESIGN.md download pinned to the RIGHT
// via `justify-between`  visual emphasis on DESIGN.md because it's the
// actual artifact users come here to grab. Other files exist for users
// who want the underlying tokens or framework-ready CSS shorthand.
//
// SERVER component: zero client JS. Each button is a plain `<a href
// download>` pointing at /api/example/<brand>/<file>. The browser
// handles the download natively, so the file contents never have to
// be embedded as React props (which previously bloated brand pages by
// 1.8 MB on Wise because the full tokens.json was serialized into the
// hydration payload). The API route streams the file with `cache-
// control: public, max-age=3600, s-maxage=86400` so repeat visits hit
// the cache and the file is only paid for on first download click.

export function BrandDownloads({
  brand,
  hasDesignMd,
  hasTokensJson,
  hasTailwindCss,
  hasShadcnCss,
}: {
  brand: string;
  /** Whether examples/<brand>/DESIGN.md exists. Always true for curated
   *  brands; the prop exists as a hard gate so the primary CTA can be
   *  hidden gracefully if a brand somehow lacks the file. */
  hasDesignMd: boolean;
  /** Whether examples/<brand>/tokens.json exists. Always true for live
   *  brands (loadBrand wouldn't return data otherwise) but kept as a
   *  flag for symmetry with the other artifacts. */
  hasTokensJson: boolean;
  /** Whether examples/<brand>/tailwind.css exists. Generated by
   *  `pnpm engine:emit-css`; can be missing if the script hasn't run
   *  for a freshly-extracted brand. */
  hasTailwindCss: boolean;
  /** Whether examples/<brand>/shadcn-theme.css exists. Null for brands
   *  where the emitter wrote shadcn-omit-reason.md instead (e.g. IBM,
   *  Stripe  their ramp data doesn't map onto shadcn's slot system). */
  hasShadcnCss: boolean;
}) {
  // Secondary artifacts on the left. Each renders as a standard blue
  // bubble so the right-aligned DESIGN.md button (green tone) reads
  // as the primary CTA without needing extra emphasis here.
  const secondary: Array<{ file: string; label: string }> = [];
  if (hasTokensJson) {
    secondary.push({ file: "tokens.json", label: "tokens.json" });
  }
  if (hasTailwindCss) {
    secondary.push({ file: "tailwind.css", label: "tailwind.css" });
  }
  if (hasShadcnCss) {
    secondary.push({ file: "shadcn-theme.css", label: "shadcn-theme.css" });
  }

  return (
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div className="flex flex-wrap items-center gap-2">
        {secondary.map(({ file, label }) => (
          <DownloadAnchor
            key={file}
            brand={brand}
            file={file}
            label={label}
          />
        ))}
      </div>
      {hasDesignMd && (
        <DownloadAnchor
          brand={brand}
          file="DESIGN.md"
          label="DESIGN.md"
          tone="green"
        />
      )}
    </div>
  );
}

// Inline server-rendered anchor styled to match <BubbleButton>. We don't
// reuse <BubbleButton> directly because it routes through next/link,
// which can interfere with the browser's native `download` behaviour on
// some Next.js versions (Link triggers client-side navigation, then
// reroutes). A plain `<a>` is simpler and guaranteed to behave like a
// download link  no JS needed.
function DownloadAnchor({
  brand,
  file,
  label,
  tone = "blue",
}: {
  brand: string;
  file: string;
  label: string;
  tone?: "blue" | "green";
}): ReactNode {
  const className = [
    "bubble-btn",
    tone === "green" ? "bubble-btn--green" : "",
  ]
    .filter(Boolean)
    .join(" ");
  const href = `/api/example/${encodeURIComponent(brand)}/${encodeURIComponent(file)}`;
  const downloadName = `${brand}.${file}`;
  return (
    <a
      href={href}
      download={downloadName}
      aria-label={`Download ${label}`}
      className={className}
    >
      <span className="bubble-btn__text">{label}</span>
      <span className="bubble-btn__icon" aria-hidden="true">
        ↓
      </span>
    </a>
  );
}
